learning_rate: 0.0001
max_gradient_norm: 5.0
batch_size: 128
num_hidden_units: 256
embedding_size: 150
num_layers: 2
dropout: 0.6
en_vocab_size: 200000
ckpt_dir: checkpoints
num_classes: 263
input_traindata: /home/jin/graduate/data_tfrecords/graduate/train.tfrecords
input_validdata: /home/jin/graduate/data_tfrecords/graduate/valid.tfrecords
valid_step: 30
valid_num_batch: 53
log_dir: /home/jin/graduate/log
vocab_dict: /home/jin/graduate/data/graduate/vocab.dict
w2v_model: /home/jin/graduate/word2vec/graduate/w2v_model
pos_weight: 40000
max_time_step_size: 1000
valid_logdir: /home/jin/graduate/valid_log/log
sig_value: 0.5