rnn_unit: lstm
learning_rate: !!float 0.01
max_gradient_norm: 5.0
batch_size: 64
num_hidden_units: 300
num_layers: 2
dropout: 0.8
en_vocab_size: 100000
ckpt_dir: checkpoints
num_classes: 183
input_traindata: /home/jin/graduate/data_tfrecords/train_batch64.tfrecords
input_validdata: /home/jin/graduate/data_tfrecords/valid.tfrecords
valid_step: 5
valid_num_batch: 5
log_dir: /home/jin/graduate/log
vocab_dict: /home/jin/graduate/data/vocab.dict
max_time_step_size: 1000